### ISSUE TITLE
Notas Gerias Ficha 3

### ISSUE THREAD

**Issue by davidrobert99** [pdarwin/repnovo#8]
Falta o diagrama UML. Porque há construtores com o super()?

De resto parece-me bem.

**Comment by pdarwin** [comment]
Olá! Os construtores têm super() porque o Eclipse os gera automaticamente assim... Como parece que há quem ache isso boa prática, nunca me importei em os tirar

**Comment by pdarwin** [comment]
Removi os super() dos construtores, e adicionei o UML ao readme
